// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeYkQHQdIkeb5JDnhiyPuSSujysqCokV0',
    appId: '1:456688600907:web:d9df6dcbc975d3406b0ace',
    messagingSenderId: '456688600907',
    projectId: 'hiking-uas-beryl',
    authDomain: 'hiking-uas-beryl.firebaseapp.com',
    storageBucket: 'hiking-uas-beryl.firebasestorage.app',
    measurementId: 'G-WM9B7BWMXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDSP_8tK_SoyeJm_6nGvBCdz1YEh2zKog',
    appId: '1:456688600907:android:06a85502201b389f6b0ace',
    messagingSenderId: '456688600907',
    projectId: 'hiking-uas-beryl',
    storageBucket: 'hiking-uas-beryl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRf43p1_SzxvFmmXMhIYXMRqD5AcxVq7Q',
    appId: '1:456688600907:ios:62acb68576072fda6b0ace',
    messagingSenderId: '456688600907',
    projectId: 'hiking-uas-beryl',
    storageBucket: 'hiking-uas-beryl.firebasestorage.app',
    iosBundleId: 'com.example.hikingWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRf43p1_SzxvFmmXMhIYXMRqD5AcxVq7Q',
    appId: '1:456688600907:ios:62acb68576072fda6b0ace',
    messagingSenderId: '456688600907',
    projectId: 'hiking-uas-beryl',
    storageBucket: 'hiking-uas-beryl.firebasestorage.app',
    iosBundleId: 'com.example.hikingWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeYkQHQdIkeb5JDnhiyPuSSujysqCokV0',
    appId: '1:456688600907:web:820346468bba194f6b0ace',
    messagingSenderId: '456688600907',
    projectId: 'hiking-uas-beryl',
    authDomain: 'hiking-uas-beryl.firebaseapp.com',
    storageBucket: 'hiking-uas-beryl.firebasestorage.app',
    measurementId: 'G-CQHJELD0P9',
  );
}
